version: "0.0.1"

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      - redis

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  redis:
    driver: local
