version: "0.0.1"

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
    networks:
      - mynetwork

networks:
  mynetwork:
